<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Insert_Location</name>
   <tag></tag>
   <elementGuidId>c776c997-0dbc-4c3b-a6a8-6878929f4a47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='select2-drop']//div[@class='select2-search']/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='select2-drop']//div[@class='select2-search']/input</value>
   </webElementProperties>
</WebElementEntity>
