<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Admins</name>
   <tag></tag>
   <elementGuidId>afe4499a-1164-48f9-bbaa-aea6c0349b93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;ACCOUNTS&quot;)/li[1]/a[1][count(. | //a[@href = 'http://www.phptravels.net/admin/accounts/admins/' and (text() = 'Admins' or . = 'Admins')]) = count(//a[@href = 'http://www.phptravels.net/admin/accounts/admins/' and (text() = 'Admins' or . = 'Admins')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;ACCOUNTS&quot;]/li[1]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://www.phptravels.net/admin/accounts/admins/</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Admins</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ACCOUNTS&quot;)/li[1]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
